import type { AirdropRow } from "@/lib/supabase/types";

/**
 * Fallback / seed airdrops shown when Supabase isn't configured yet, or when
 * the database is empty. Once you run the migration + add real airdrops via
 * the /admin panel, these become a fallback only.
 */
export const DEMO_AIRDROPS: AirdropRow[] = [
  {
    id: "demo-linea",
    slug: "linea-points-airdrop",
    name: "Linea Points Program",
    chain: "ethereum",
    description:
      "Earn Linea Voyage XP by using dApps on Linea L2. Speculated token airdrop based on XP.",
    estimated_value_usd: 500,
    estimated_value_inr: 41500,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 90).toISOString(),
    difficulty: "easy",
    status: "active",
    logo_url: null,
    official_url: "https://linea.build/hub",
    steps: [
      {
        title: "Bridge ETH to Linea",
        body: "Use the official Linea bridge to move a small amount of ETH (₹2k+) from mainnet to Linea.",
      },
      {
        title: "Use 3-5 dApps",
        body: "Swap on Lynex/Echodex, lend on Mendi/ZeroLend, mint an NFT, and interact with bridges.",
      },
      {
        title: "Mint Voyage XP",
        body: "Visit linea.build/hub each week and claim weekly XP via active tasks.",
      },
      {
        title: "Stay consistent",
        body: "Sybil filters punish single-day farmers. Spread activity across weeks.",
      },
    ],
    tags: ["L2", "Ethereum", "Points"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-zksync",
    slug: "zksync-era-followup",
    name: "zkSync Era Follow-up Airdrop",
    chain: "ethereum",
    description:
      "Second-wave airdrop expected for users who missed the first ZK allocation or are active on ZKsync ecosystem.",
    estimated_value_usd: 300,
    estimated_value_inr: 24900,
    deadline: null,
    difficulty: "medium",
    status: "upcoming",
    logo_url: null,
    official_url: "https://zksync.io",
    steps: [
      { title: "Bridge to zkSync Era", body: "Use the native bridge or Orbiter." },
      { title: "Swap on SyncSwap / Mute", body: "5+ swaps across multiple weeks." },
      { title: "Use a lending dApp", body: "Try Reactor Fusion or ZeroLend on zkSync." },
      { title: "Mint an NFT", body: "Mint a low-cost NFT to register on-chain activity." },
    ],
    tags: ["L2", "Ethereum", "zk"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-solana-jito",
    slug: "jito-restaking-points",
    name: "Jito Restaking Points",
    chain: "solana",
    description:
      "Stake SOL via Jito's liquid restaking. Accumulate points, expected to convert to JTO tokens.",
    estimated_value_usd: 200,
    estimated_value_inr: 16600,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
    difficulty: "easy",
    status: "active",
    logo_url: null,
    official_url: "https://jito.network",
    steps: [
      { title: "Get SOL", body: "Buy SOL on CoinDCX/WazirX and withdraw to Phantom wallet." },
      { title: "Stake via Jito", body: "Visit jito.network and stake your SOL into JitoSOL." },
      { title: "Hold for points", body: "Points accumulate continuously while staked." },
    ],
    tags: ["Solana", "Restaking"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-eigenlayer",
    slug: "eigenlayer-restaking",
    name: "EigenLayer Restaking Points",
    chain: "ethereum",
    description:
      "Restake ETH or LSTs (stETH, rETH) via EigenLayer. Points accrue and are speculated to convert to EIGEN tokens.",
    estimated_value_usd: 800,
    estimated_value_inr: 66400,
    deadline: null,
    difficulty: "medium",
    status: "active",
    logo_url: null,
    official_url: "https://eigenlayer.xyz",
    steps: [
      { title: "Acquire stETH / rETH", body: "Bridge or buy a liquid staked ETH derivative." },
      { title: "Deposit on EigenLayer", body: "Go to app.eigenlayer.xyz and deposit." },
      { title: "Delegate to operators", body: "Pick an operator to delegate your restaked tokens." },
    ],
    tags: ["Restaking", "Ethereum"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-base-points",
    slug: "base-l2-activity",
    name: "Base L2 Activity (Coinbase)",
    chain: "base",
    description:
      "Coinbase's Base L2 has hinted at a future token. Stay active across DeFi, NFTs, and social on Base.",
    estimated_value_usd: 250,
    estimated_value_inr: 20750,
    deadline: null,
    difficulty: "easy",
    status: "active",
    logo_url: null,
    official_url: "https://base.org",
    steps: [
      { title: "Bridge to Base", body: "Use the official Base bridge or a 3rd-party L0/Stargate." },
      { title: "Mint a Base NFT", body: "Cheap on-chain NFTs (Zora, etc.)" },
      { title: "Swap on Aerodrome", body: "Aerodrome is Base's flagship DEX." },
    ],
    tags: ["L2", "Coinbase"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-arbitrum-stip",
    slug: "arbitrum-stip-rounds",
    name: "Arbitrum STIP Rounds",
    chain: "arbitrum",
    description:
      "Arbitrum's Short-Term Incentive Program rewards users of selected protocols with ARB grants.",
    estimated_value_usd: 150,
    estimated_value_inr: 12450,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    difficulty: "easy",
    status: "active",
    logo_url: null,
    official_url: "https://forum.arbitrum.foundation",
    steps: [
      { title: "Find an active STIP protocol", body: "Check the Arbitrum forum for current STIP recipients." },
      { title: "Deposit / trade", body: "Provide liquidity or trade on the protocol." },
      { title: "Wait for distribution", body: "Rewards typically distributed weekly or monthly in ARB." },
    ],
    tags: ["L2", "ARB"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-bnb-megadrop",
    slug: "bnb-chain-megadrop",
    name: "BNB Chain Megadrop",
    chain: "bnb",
    description:
      "Binance's Megadrop platform — lock BNB or complete tasks for early-stage token drops.",
    estimated_value_usd: 100,
    estimated_value_inr: 8300,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    difficulty: "easy",
    status: "active",
    logo_url: null,
    official_url: "https://www.binance.com/en/megadrop",
    steps: [
      { title: "Hold BNB on Binance", body: "Hold BNB in your Binance Spot wallet (locked subscription available)." },
      { title: "Complete tasks", body: "Sign in, trade, complete Web3 quests via Binance Web3 wallet." },
      { title: "Claim tokens", body: "Once the campaign ends, claim your token allocation." },
    ],
    tags: ["BNB", "Binance"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-polygon-zkevm",
    slug: "polygon-zkevm-airdrop",
    name: "Polygon zkEVM Activity",
    chain: "polygon",
    description:
      "Polygon has launched MATIC→POL migration and a unified zk stack. Activity may translate to future drops.",
    estimated_value_usd: 80,
    estimated_value_inr: 6640,
    deadline: null,
    difficulty: "medium",
    status: "active",
    logo_url: null,
    official_url: "https://polygon.technology",
    steps: [
      { title: "Bridge to zkEVM", body: "Use the official Polygon Portal." },
      { title: "Use Polygon DeFi", body: "Try QuickSwap, Aave, or a lending protocol on zkEVM." },
      { title: "Track POL rewards", body: "Stake POL and earn rewards across Polygon's chains." },
    ],
    tags: ["Polygon", "zkEVM"],
    ai_generated_guide: false,
    views: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
