import * as React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import type { TaxInput, TaxResult } from "@/lib/tax/calculator";

const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#0a0a0a",
    color: "#fafafa",
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 11,
  },
  brand: {
    fontSize: 18,
    fontWeight: 700,
    color: "#a78bfa",
    marginBottom: 4,
  },
  h1: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 16,
  },
  section: {
    marginBottom: 14,
    paddingBottom: 10,
    borderBottom: "1pt solid #2a2a2a",
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#a78bfa",
    marginBottom: 6,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  label: {
    color: "#a1a1aa",
  },
  value: {
    color: "#fafafa",
    fontWeight: 600,
  },
  accentValue: {
    color: "#a78bfa",
    fontWeight: 700,
  },
  footer: {
    marginTop: 24,
    fontSize: 9,
    color: "#71717a",
    lineHeight: 1.4,
  },
  netBox: {
    backgroundColor: "#241a39",
    padding: 14,
    borderRadius: 8,
    marginTop: 10,
    marginBottom: 14,
  },
  netLabel: {
    fontSize: 10,
    color: "#c4b5fd",
    marginBottom: 4,
  },
  netValue: {
    fontSize: 18,
    fontWeight: 700,
    color: "#fff",
  },
});

function inr(n: number): string {
  if (!Number.isFinite(n)) return "Rs. 0";
  return `Rs. ${new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(n)}`;
}

function TaxPdf({ input, result }: { input: TaxInput; result: TaxResult }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>CryptoTaxIndia</Text>
        <Text style={styles.h1}>Tax Summary — Section 115BBH &amp; 194S</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Trade details</Text>
          <Row label="Asset" value={input.assetName ?? "Crypto"} />
          <Row label="Buy price" value={inr(input.buyPrice)} />
          <Row label="Sell price" value={inr(input.sellPrice)} />
          <Row label="Quantity" value={String(input.quantity)} />
          {input.buyDate && <Row label="Buy date" value={input.buyDate} />}
          {input.sellDate && <Row label="Sell date" value={input.sellDate} />}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>P&amp;L</Text>
          <Row label="Total buy value" value={inr(result.totalBuy)} />
          <Row label="Total sell value" value={inr(result.totalSell)} />
          <Row
            label={result.isProfit ? "Profit" : "Loss"}
            value={inr(result.profitLoss)}
            accent
          />
          <Row label="Taxable gain" value={inr(result.taxableGain)} />
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Tax calculation</Text>
          <Row label="Base tax (30%)" value={inr(result.baseTax)} />
          {result.surcharge > 0 && (
            <Row
              label={`Surcharge (${(result.surchargeRate * 100).toFixed(0)}%)`}
              value={inr(result.surcharge)}
            />
          )}
          <Row label="Health & Education cess (4%)" value={inr(result.cess)} />
          <Row label="Total tax payable" value={inr(result.totalTax)} accent />
          <Row label="TDS u/s 194S (1%)" value={inr(result.tds)} />
          <Row
            label="Effective rate"
            value={`${(result.effectiveRate * 100).toFixed(2)}%`}
          />
        </View>

        <View style={styles.netBox}>
          <Text style={styles.netLabel}>Net cash after tax + TDS</Text>
          <Text style={styles.netValue}>{inr(result.netCashFromSale)}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Notes</Text>
          {result.notes.map((n, i) => (
            <Text key={i} style={{ color: "#a1a1aa", marginBottom: 3 }}>
              {"\u2022 "}
              {n}
            </Text>
          ))}
        </View>

        <Text style={styles.footer}>
          This report is informational only and not a substitute for professional
          tax advice. Indian crypto tax is governed by Sections 115BBH and 194S
          of the Income-tax Act, 1961. Always validate with a Chartered
          Accountant before filing your ITR. Generated by AirdropIndia /
          CryptoTaxIndia.
        </Text>
      </Page>
    </Document>
  );
}

function Row({
  label,
  value,
  accent,
}: {
  label: string;
  value: string;
  accent?: boolean;
}) {
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={accent ? styles.accentValue : styles.value}>{value}</Text>
    </View>
  );
}

export async function renderTaxPdf({
  input,
  result,
}: {
  input: TaxInput;
  result: TaxResult;
}): Promise<Buffer> {
  const buf = await renderToBuffer(<TaxPdf input={input} result={result} />);
  return buf as Buffer;
}
