import { NextResponse, type NextRequest } from "next/server";
import { calculateTax, type SurchargeBracket, type TaxInput, type TaxResult } from "@/lib/tax/calculator";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function inr(n: number): string {
  if (!Number.isFinite(n)) return "Rs. 0";
  return `Rs. ${new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 }).format(n)}`;
}

function buildPlainTextPdf(input: TaxInput, result: TaxResult): string {
  const lines: string[] = [];
  lines.push("CryptoTaxIndia — Tax Summary");
  lines.push("Section 115BBH & 194S");
  lines.push("=".repeat(50));
  lines.push("");
  lines.push("TRADE DETAILS");
  lines.push(`  Asset:        ${input.assetName ?? "Crypto"}`);
  lines.push(`  Buy price:    ${inr(input.buyPrice)}`);
  lines.push(`  Sell price:   ${inr(input.sellPrice)}`);
  lines.push(`  Quantity:     ${input.quantity}`);
  if (input.buyDate) lines.push(`  Buy date:     ${input.buyDate}`);
  if (input.sellDate) lines.push(`  Sell date:    ${input.sellDate}`);
  lines.push("");
  lines.push("PROFIT & LOSS");
  lines.push(`  Total buy:    ${inr(result.totalBuy)}`);
  lines.push(`  Total sell:   ${inr(result.totalSell)}`);
  lines.push(`  ${result.isProfit ? "Profit" : "Loss"}:       ${inr(result.profitLoss)}`);
  lines.push(`  Taxable gain: ${inr(result.taxableGain)}`);
  lines.push("");
  lines.push("TAX CALCULATION");
  lines.push(`  Base tax (30%):              ${inr(result.baseTax)}`);
  if (result.surcharge > 0) {
    lines.push(`  Surcharge (${(result.surchargeRate * 100).toFixed(0)}%):             ${inr(result.surcharge)}`);
  }
  lines.push(`  Health & Education cess (4%): ${inr(result.cess)}`);
  lines.push(`  Total tax payable:           ${inr(result.totalTax)}`);
  lines.push(`  TDS u/s 194S (1%):           ${inr(result.tds)}`);
  lines.push(`  Effective rate:              ${(result.effectiveRate * 100).toFixed(2)}%`);
  lines.push("");
  lines.push("=".repeat(50));
  lines.push(`  NET CASH AFTER TAX + TDS:    ${inr(result.netCashFromSale)}`);
  lines.push("=".repeat(50));
  lines.push("");
  lines.push("NOTES");
  result.notes.forEach((n) => lines.push(`  • ${n}`));
  lines.push("");
  lines.push("-".repeat(50));
  lines.push("This report is informational only and not a substitute for professional");
  lines.push("tax advice. Indian crypto tax is governed by Sections 115BBH and 194S");
  lines.push("of the Income-tax Act, 1961. Always validate with a Chartered");
  lines.push("Accountant before filing your ITR. Generated by AirdropIndia.");
  return lines.join("\n");
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const buyPrice = parseFloat(searchParams.get("buyPrice") ?? "0");
  const sellPrice = parseFloat(searchParams.get("sellPrice") ?? "0");
  const quantity = parseFloat(searchParams.get("quantity") ?? "0");
  const buyDate = searchParams.get("buyDate") ?? "";
  const sellDate = searchParams.get("sellDate") ?? "";
  const asset = searchParams.get("asset") ?? "";
  const surcharge = parseFloat(searchParams.get("surcharge") ?? "0") as SurchargeBracket;
  const specifiedPerson = searchParams.get("specifiedPerson") === "1";
  const yearlyTransferTotal = parseFloat(searchParams.get("yearlyTransferTotal") ?? "0");

  const input: TaxInput = {
    assetName: asset || undefined,
    buyPrice,
    sellPrice,
    quantity,
    buyDate,
    sellDate,
    surchargeOverride: surcharge,
    isSpecifiedPerson: specifiedPerson,
    yearlyTransferTotal: yearlyTransferTotal || undefined,
  };
  const result = calculateTax(input);

  // Try react-pdf first, fall back to plain text download
  try {
    const { renderTaxPdf } = await import("@/lib/tax/pdf");
    const buffer = await renderTaxPdf({ input, result });
    const body = new Uint8Array(buffer);
    return new NextResponse(body, {
      status: 200,
      headers: {
        "content-type": "application/pdf",
        "content-disposition": `attachment; filename="CryptoTaxIndia-${Date.now()}.pdf"`,
      },
    });
  } catch (e) {
    console.error("PDF render error, falling back to text:", e);
  }

  // Fallback: return as downloadable text file
  const text = buildPlainTextPdf(input, result);
  return new NextResponse(text, {
    status: 200,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "content-disposition": `attachment; filename="CryptoTaxIndia-${Date.now()}.txt"`,
    },
  });
}
